# Generated by Django 5.1.2 on 2025-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=255, verbose_name='自動化してほしいシステムの名称')),
                ('industry', models.CharField(choices=[('農業、林業', '農業、林業'), ('建設業', '建設業'), ('製造業', '製造業'), ('運輸業', '運輸業'), ('卸売業、小売業', '卸売業、小売業'), ('不動産業', '不動産業'), ('飲食業', '飲食業'), ('教育、学習支援', '教育、学習支援'), ('医療，福祉', '医療，福祉'), ('行政', '行政'), ('その他', 'その他')], max_length=50, verbose_name='業態')),
                ('other_industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='業態（その他）')),
                ('manual_file', models.FileField(blank=True, null=True, upload_to='manuals/', verbose_name='マニュアル')),
                ('contact_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='連絡先（宛名・メールアドレス）')),
                ('other', models.CharField(blank=True, max_length=255, null=True, verbose_name='その他')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
            ],
        ),
    ]
